[package]
name = "Strustegy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
dashmap = "5.4.0"
quote = "1.0.28"
regex = "1.8.4"
syn = "2.0.18"
